2nex -> nex

diff --git a/env/bootstrap-phase1.yaml b/env/bootstrap-phase1.yaml
--- a/env/bootstrap-phase1.yaml
+++ b/env/bootstrap-phase1.yaml
@@ -5,8 +5,8 @@ execution:
   chroot: true
 
 paths:
-  work: 2nex/work
-  out: 2nex/out
+  work: nex/work
+  out: nex/out
   inputs: inputs
 
 env:
@@ -18,9 +18,9 @@ env:
   GLIBC_TUNABLES: glibc.cpu.hwcaps=-RNDRAND
   MAKEFLAGS: "-j{num_cpus}"
   PATH: /usr/bin:/bin
-  TARGET: x86_64-2nex-linux-gnu
-  WORK_DIR: /2nex/work
-  OUT_DIR: /2nex/out
+  TARGET: x86_64-nex-linux-gnu
+  WORK_DIR: /nex/work
+  OUT_DIR: /nex/out
   AR: gcc-ar
   NM: gcc-nm
   RANLIB: gcc-ranlib
@@ -30,13 +30,13 @@ env:
 
 preamble: |
   if ! read -r current_hostname < /proc/sys/kernel/hostname; then
-      echo 'Warning: Could not read current hostname; forcing to 2nex-builder' >&2
+      echo 'Warning: Could not read current hostname; forcing to nex-builder' >&2
       current_hostname=""
   fi
 
-  if [ "$current_hostname" != "2nex-builder" ]; then
-      echo 'Setting hostname to 2nex-builder'
-      if ! hostname 2nex-builder; then
+  if [ "$current_hostname" != "nex-builder" ]; then
+      echo 'Setting hostname to nex-builder'
+      if ! hostname nex-builder; then
           echo 'Warning: Failed to run hostname command' >&2
       fi
   fi
